
name: cuboids_pami
channels:
  - pytorch
  - conda-forge
  - pytorch3d
  - iopath
  - bottler
  - fvcore
  - defaults
dependencies:
  - matplotlib
  - numpy
  - python=3.9
  - pytorch=1.10.1
  - cudatoolkit=11.3
  - mkl=2024.0
  - iopath
  - nvidiacub
  - fvcore
  - scikit-image
  - scikit-learn
  - scipy
  - pytorch3d
  - opencv=4.7.0
  - pip
  - pip:
    - wandb
    - open3d==0.18.0
